<a href="https://colab.research.google.com/github/Aiswarya-2sathyakumar/ICT_DSA-2026/blob/main/Casestudy%20on%20sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [108]:
import sqlite3
import pandas as pd

In [109]:
def load_imdb_database(db_path):
  try:
    conn = sqlite3.connect(db_path)
    print("IMDB database loaded successfully.")
    return conn
  except sqlite3.Error as e:
    print(f"Error loading IMDB database: {e}")
    return None

In [110]:
db_path = "imdb.db"
conn = load_imdb_database(db_path)

if conn:
  print("Connection successful")
  cursor = conn.cursor()

IMDB database loaded successfully.
Connection successful

In [111]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

print("Database Schema:")
for table in tables:
    table_name = table[0]
    print(f"\nTable: {table_name}")

    cursor.execute(f"PRAGMA table_info({table_name});")
    schema = cursor.fetchall()

    print("Columns:")
    for column in schema:
        cid, name, dtype, notnull, dflt_value, pk = column
        print(f"  - {name} ({dtype}), NOT NULL: {bool(notnull)}, Default: {dflt_value}, Primary Key: {bool(pk)}")

Database Schema:

Table: students
Columns:
  - id (INTEGER), NOT NULL: False, Default: None, Primary Key: True
  - name (VARCHAR(100)), NOT NULL: False, Default: None, Primary Key: False

Table: Person
Columns:
  - pid (INTEGER), NOT NULL: False, Default: None, Primary Key: True
  - name (TEXT), NOT NULL: False, Default: None, Primary Key: False

Table: Movie
Columns:
  - mid (INTEGER), NOT NULL: False, Default: None, Primary Key: True
  - title (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - year (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - rating (REAL), NOT NULL: False, Default: None, Primary Key: False
  - num_votes (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: Country
Columns:
  - CID (INTEGER), NOT NULL: False, Default: None, Primary Key: True
  - Name (TEXT), NOT NULL: False, Default: None, Primary Key: False

Table: M_Country
Columns:
  - MID (INTEGER), NOT NULL: False, Default: None, Primary Key: True
  - CID (INTEGER), NOT NULL: False, Default: None, Primary Key: True

Table: Language
Columns:
  - LAID (INTEGER), NOT NULL: False, Default: None, Primary Key: True
  - Name (TEXT), NOT NULL: False, Default: None, Primary Key: False

Table: M_Language
Columns:
  - MID (INTEGER), NOT NULL: False, Default: None, Primary Key: True
  - LAID (INTEGER), NOT NULL: False, Default: None, Primary Key: True

In [165]:
if conn:
    conn.close()

conn = load_imdb_database(db_path)

q1 = "SELECT * FROM Person LIMIT 5;"
result = pd.read_sql_query (q1,conn)
result

IMDB database loaded successfully.

   pid              name
0    1    Shah Rukh Khan
1    2             Kajol
2    3        Aamir Khan
3    4  Deepika Padukone
4    5       Salman Khan

In [166]:
def q1_grader(q1):
  result = pd.read_sql_query(q1, conn)
  return result.shape == (5, 4)
print(q1_grader(q1))

False

In [121]:
q2 = "SELECT title,year,rating FROM Movie ;" # Corrected table name to 'Movie'
result = pd.read_sql_query (q2,conn)
result

                         title  year  rating
0  Dilwale Dulhania Le Jayenge  1995     8.1
1                     3 Idiots  2009     8.4
2                       Devdas  2002     7.6
3              Chennai Express  2013     6.0
4                 The Avengers  2012     8.0
5                     Alam Ara  1931     7.0
6      Bahubali: The Beginning  2015     8.0
7                    Padmaavat  2018     7.0
8     Uri: The Surgical Strike  2019     8.2

In [122]:
def q2_grader(q2):
  result = pd.read_sql_query(q2, conn)
  return result.shape == (3473, 3) and result['title'][0]=='Mowgli'
print(q2_grader(q2))

False

In [123]:
q3 ='SELECT title FROM Movie ORDER BY year ASC LIMIT 1;' # Corrected table name to 'Movie'
result = pd.read_sql_query (q3,conn)
result

      title
0  Alam Ara

In [124]:
def q3_grader(q3):
  result = pd.read_sql_query(q3, conn)
  return result['title']=='Alam Ara'
print(q3_grader(q3))

0    True
Name: title, dtype: bool

In [125]:
q4 = "SELECT year FROM Movie WHERE title ='Devdas' ORDER BY year ASC LIMIT 1;" # Corrected table name to 'Movie'
result = pd.read_sql_query (q4,conn)
result

   year
0  2002

In [126]:
def q4_grader(q4):
  result = pd.read_sql_query(q4, conn)
  return result['year']=='1936'
print(q4_grader(q4))

0    False
Name: year, dtype: bool

In [127]:
q5 = "SELECT COUNT(title) FROM Movie WHERE year = 2018;" # Corrected table name to 'Movie'
result = pd.read_sql_query (q5,conn)
result

   COUNT(title)
0             1

In [128]:
def q5_grader(q5):
  result = pd.read_sql_query(q5, conn)
  return result.iloc[0, 0] == 93
print(q5_grader(q5))

False

In [129]:
q6 ="SELECT title FROM Movie WHERE year = 2012 ORDER BY num_votes DESC LIMIT 1;" # Corrected table name to 'Movie'
result = pd.read_sql_query (q6,conn)
result

          title
0  The Avengers

In [130]:
def q6_grader(q6):
  result = pd.read_sql_query(q6, conn)
  return result["title"]=="The Avengers"
print(q6_grader(q6))

0    True
Name: title, dtype: bool

In [131]:
q7 = "SELECT DISTINCT title FROM Movie WHERE year = 2018;" # Corrected table name to 'Movie'
result = pd.read_sql_query (q7,conn)
result

       title
0  Padmaavat

In [132]:
def q7_grader(q7):
  result = pd.read_sql_query(q7, conn)
  return result.shape==(93, 1)
print(q7_grader(q7))

False

In [133]:
q8 ="SELECT COUNT(title) FROM Movie WHERE year BETWEEN 2017 AND 2018;" # Corrected table name to 'Movie'
result = pd.read_sql_query (q8,conn)
result

   COUNT(title)
0             1

In [134]:
def q8_grader(q8):
  result = pd.read_sql_query(q8, conn)
  return result.iloc[0, 0] == 211
print(q8_grader(q8))

False

In [135]:
q9 = "SELECT year, COUNT(*) AS title FROM Movie GROUP BY year ORDER BY COUNT(title) DESC LIMIT 1;" # Corrected table name to 'Movie'
result = pd.read_sql_query (q9,conn)
result

   year  title
0  2019      1

In [136]:
def q9_grader(q9):
  result = pd.read_sql_query(q9, conn)
  return result["year"][0]=="2005"
print(q9_grader(q9))

False

In [137]:
q10 = "SELECT title FROM Movie WHERE rating >9.5 AND num_votes >90;"
result = pd.read_sql_query (q10,conn)
result

Empty DataFrame
Columns: [title]
Index: []

In [138]:
def q10_grader(q10):
  result = pd.read_sql_query(q10, conn)
  if not result.empty:
    return result["title"][0]=="Man on Mission Fauladi"
  return False
print(q10_grader(q10))

False

In [139]:
q11 = "SELECT COUNT(title) FROM Movie WHERE title LIKE '%Dilwale%'; " # Corrected table name to 'Movie'
result = pd.read_sql_query (q11,conn)
result

   COUNT(title)
0             1

In [140]:
def q11_grader(q11):
  result = pd.read_sql_query(q11, conn)
  return result.iloc[0, 0] == 4
print(q11_grader(q11))

False

In [141]:
q12 = "SELECT CID FROM M_Country GROUP BY CID ORDER BY COUNT(*) DESC LIMIT 1; " # Corrected table name to 'M_Country'
result = pd.read_sql_query (q12,conn)
result

   CID
0    2

In [142]:
def q12_grader(q12):
  result = pd.read_sql_query(q12, conn)
  return result.iloc[0]==2.0
print(q12_grader(q12))

CID    True
Name: 0, dtype: bool

In [143]:
q13 =  """
SELECT Name
FROM Country
WHERE CID = (
    SELECT CID
    FROM M_Country
    GROUP BY CID
    ORDER BY COUNT(*) DESC
    LIMIT 1
);
"""

pd.read_sql_query(q13 , conn)

    Name
0  India

In [144]:
def q13_grader(q13):
  result = pd.read_sql_query(q13, conn)
  return result.iloc[0, 0] == "India"
print(q13_grader(q13))

True

In [145]:
q14 ="SELECT year, COUNT(*) AS movie_count FROM Movie GROUP BY year HAVING COUNT(*) > 100;" # Corrected table name to 'Movie'
result = pd.read_sql_query(q14 , conn)
result

Empty DataFrame
Columns: [year, movie_count]
Index: []

In [146]:
def q14_grader(q14):
  result = pd.read_sql_query(q14, conn)
  return result.shape==(13,2)
print(q14_grader(q14))

False

In [147]:
q15 = "SELECT name, LAID FROM language WHERE name = 'Malayalam';"
#q15 ="SELECT * FROM language"
result = pd.read_sql_query(q15 , conn)
result

        Name  LAID
0  Malayalam    19

In [148]:
def q15_grader(q15):
  result = pd.read_sql_query(q15, conn)
  print(result)
  return result[["Name", "LAID"]].values.tolist() == [['Malayalam', 19]]
print(q15_grader(q15))

        Name  LAID
0  Malayalam    19
True

In [149]:
q16 = "SELECT m.mid, m.title, ml.laid FROM Movie m INNER JOIN M_Language ml ON m.mid = ml.mid;" # Corrected table names to 'Movie' and 'M_Language'
result = pd.read_sql_query(q16 , conn)
result

   mid                        title  LAID
0  101  Dilwale Dulhania Le Jayenge     2
1  105                 The Avengers     1
2  107      Bahubali: The Beginning    19
3  108                    Padmaavat     2

In [150]:
def q16_grader(q16):
  result = pd.read_sql_query(q16, conn)
  return result
print(q16_grader(q16))

   mid                        title  LAID
0  101  Dilwale Dulhania Le Jayenge     2
1  105                 The Avengers     1
2  107      Bahubali: The Beginning    19
3  108                    Padmaavat     2

In [168]:
q17 = "SELECT m.title, m.year, m.rating FROM Movie m INNER JOIN M_Language ml ON m.mid = ml.mid WHERE ml.laid = 19;" # Corrected table names to 'Movie' and 'M_Language'
result = pd.read_sql_query(q17 , conn)
result

                     title  year  rating
0  Bahubali: The Beginning  2015     8.0

In [169]:
def q17_grader(q17):
  result = pd.read_sql_query(q17, conn)
  return result.shape==(16,3)
print(q17_grader(q17))

False

In [153]:
![ -f academic.db ] && rm academic.db

conn = sqlite3.connect("academic.db")
cursor = conn.cursor()

In [154]:
q18a = """CREATE TABLE students (id INTEGER PRIMARY KEY, name VARCHAR(100));"""

#q18b = """SELECT * FROM students;"""

#q18a ="DROP TABLE IF EXISTS students;"

In [155]:
def q18_grader_a(q18):
  try:
    cursor.execute(q18)
    return True
  except:
    pass

def q18_grader_b(q19):
  result = pd.read_sql_query(q19, conn)
  return result.columns.tolist() == ['id', 'name']

q18b = """SELECT * FROM students;"""

print(q18_grader_a(q18a) and q18_grader_b(q18b))

True

In [156]:
q19_a ="INSERT INTO students (id,name) VALUES(1,'Alice')"

In [157]:
cursor.execute(q19_a)

In [171]:
q20 = "INSERT INTO students (id, name) VALUES (2, 'Bob'), (3, 'Charlie');"

In [172]:
cursor.execute(q20)

ProgrammingError: Cannot operate on a closed database.

In [173]:
q20_a = "SELECT * FROM students"
result = pd.read_sql_query(q20_a,conn)
result

   id     name
0   1    Alice
1   2      Bob
2   3  Charlie

In [174]:
def q20_grader(q20):
  try:
    cursor.execute(q20)
  except:
    pass
  return True

def q20_grader_b(q20_b):
  result = pd.read_sql_query(q20_b, conn)
  return result.values.tolist() == [[1, 'Alice'], [2, 'Bob'], [3, 'Charlie']]

print(q20_grader(q20) and q20_grader_b(q19_b))

True