<a href="https://colab.research.google.com/github/Aiswarya-2sathyakumar/ICT_DSA-2026/blob/main/Casestudy_and_Intermediate_Assessment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

#Load SpaceX Launch data and Rocket metadata from API

In [8]:
import requests
#API url
launch_url =" https://api.spacexdata.com/v4/launches"
rocket_url ="https://api.spacexdata.com/v4/rockets"
# Fetches data from API
launch_data = requests.get(launch_url).json()
rocket_data = requests.get(rocket_url).json()
#Converts data into dataframe
launch_df = pd.DataFrame(launch_data)
rocket_df = pd.DataFrame(rocket_data)

##Extract relevant columns

In [13]:
launch_df = launch_df[['name', 'date_utc', 'success', 'details', 'rocket']]
print(launch_df)

                       name                  date_utc success  \
0                 FalconSat 2006-03-24 22:30:00+00:00   False
1                   DemoSat 2007-03-21 01:10:00+00:00   False
2               Trailblazer 2008-08-03 03:34:00+00:00   False
3                    RatSat 2008-09-28 23:15:00+00:00    True
4                  RazakSat 2009-07-13 03:35:00+00:00    True
..                      ...                       ...     ...
200           Transporter-6 2022-12-01 00:00:00+00:00    None
201                   TTL-1 2022-12-01 00:00:00+00:00    None
202  WorldView Legion 1 & 2 2022-12-01 00:00:00+00:00    None
203     Viasat-3 & Arcturus 2022-12-01 00:00:00+00:00    None
204          O3b mPower 3.4 2022-12-01 00:00:00+00:00    None

                                               details  \
0     Engine failure at 33 seconds and loss of vehicle
1    Successful first stage burn and transition to ...
2    Residual stage 1 thrust led to collision betwe...
3    Ratsat was carried to orbit on the first succe...
4                                                 None
..                                                 ...
200                                               None
201                                               None
202                                               None
203                                               None
204                                               None

                       rocket
0    5e9d0d95eda69955f709d1eb
1    5e9d0d95eda69955f709d1eb
2    5e9d0d95eda69955f709d1eb
3    5e9d0d95eda69955f709d1eb
4    5e9d0d95eda69955f709d1eb
..                        ...
200  5e9d0d95eda69973a809d1ec
201  5e9d0d95eda69973a809d1ec
202  5e9d0d95eda69973a809d1ec
203  5e9d0d95eda69974db09d1ed
204  5e9d0d95eda69973a809d1ec

[205 rows x 5 columns]

##Convert date_utc to datetime

In [14]:
launch_df['date_utc'] = pd.to_datetime(launch_df['date_utc'])
print(launch_df['date_utc'])

0     2006-03-24 22:30:00+00:00
1     2007-03-21 01:10:00+00:00
2     2008-08-03 03:34:00+00:00
3     2008-09-28 23:15:00+00:00
4     2009-07-13 03:35:00+00:00
                 ...
200   2022-12-01 00:00:00+00:00
201   2022-12-01 00:00:00+00:00
202   2022-12-01 00:00:00+00:00
203   2022-12-01 00:00:00+00:00
204   2022-12-01 00:00:00+00:00
Name: date_utc, Length: 205, dtype: datetime64[ns, UTC]

##Extract the year

In [15]:
launch_df['year'] = launch_df['date_utc'].dt.year
print(launch_df['year'])

0      2006
1      2007
2      2008
3      2008
4      2009
       ...
200    2022
201    2022
202    2022
203    2022
204    2022
Name: year, Length: 205, dtype: int32

##Extract relevant columns

In [19]:
rocket_df = rocket_df[["id", "name", "type", "active", "stages"]]
print(rocket_df)

                         id          name    type  active  stages
0  5e9d0d95eda69955f709d1eb      Falcon 1  rocket   False       2
1  5e9d0d95eda69973a809d1ec      Falcon 9  rocket    True       2
2  5e9d0d95eda69974db09d1ed  Falcon Heavy  rocket    True       2
3  5e9d0d96eda699382d09d1ee      Starship  rocket   False       2

In [57]:
rocket_df.rename(columns={'id': 'rocket'}, inplace=True)
rocket_df.rename(columns={'name': 'rocket_name'}, inplace=True)
print(rocket_df)

                     rocket   rocket_name    type  active  stages
0  5e9d0d95eda69955f709d1eb      Falcon 1  rocket   False       2
1  5e9d0d95eda69973a809d1ec      Falcon 9  rocket    True       2
2  5e9d0d95eda69974db09d1ed  Falcon Heavy  rocket    True       2
3  5e9d0d96eda699382d09d1ee      Starship  rocket   False       2

#Merge Launch and Rocket Data

In [58]:
merge_df = pd.merge(launch_df, rocket_df ,on ='rocket',how = 'left')    #left(keep all launch records)
print(merge_df.head(5))

          name                  date_utc success  \
0    FalconSat 2006-03-24 22:30:00+00:00   False
1      DemoSat 2007-03-21 01:10:00+00:00   False
2  Trailblazer 2008-08-03 03:34:00+00:00   False
3       RatSat 2008-09-28 23:15:00+00:00    True
4     RazakSat 2009-07-13 03:35:00+00:00    True

                                             details  \
0   Engine failure at 33 seconds and loss of vehicle
1  Successful first stage burn and transition to ...
2  Residual stage 1 thrust led to collision betwe...
3  Ratsat was carried to orbit on the first succe...
4                                               None

                     rocket  year rocket_name    type  active  stages
0  5e9d0d95eda69955f709d1eb  2006    Falcon 1  rocket   False       2
1  5e9d0d95eda69955f709d1eb  2007    Falcon 1  rocket   False       2
2  5e9d0d95eda69955f709d1eb  2008    Falcon 1  rocket   False       2
3  5e9d0d95eda69955f709d1eb  2008    Falcon 1  rocket   False       2
4  5e9d0d95eda69955f709d1eb  2009    Falcon 1  rocket   False       2

#Add Simulated Country Information

In [60]:
import numpy as np
countries =['USA', 'Russia', 'India', 'China', 'France']
merge_df['country'] = pd.Series(np.random.choice( countries,len(merge_df)))

print(merge_df.head())

          name                  date_utc success  \
0    FalconSat 2006-03-24 22:30:00+00:00   False
1      DemoSat 2007-03-21 01:10:00+00:00   False
2  Trailblazer 2008-08-03 03:34:00+00:00   False
3       RatSat 2008-09-28 23:15:00+00:00    True
4     RazakSat 2009-07-13 03:35:00+00:00    True

                                             details  \
0   Engine failure at 33 seconds and loss of vehicle
1  Successful first stage burn and transition to ...
2  Residual stage 1 thrust led to collision betwe...
3  Ratsat was carried to orbit on the first succe...
4                                               None

                     rocket  year rocket_name    type  active  stages country
0  5e9d0d95eda69955f709d1eb  2006    Falcon 1  rocket   False       2   China
1  5e9d0d95eda69955f709d1eb  2007    Falcon 1  rocket   False       2  Russia
2  5e9d0d95eda69955f709d1eb  2008    Falcon 1  rocket   False       2  France
3  5e9d0d95eda69955f709d1eb  2008    Falcon 1  rocket   False       2  Russia
4  5e9d0d95eda69955f709d1eb  2009    Falcon 1  rocket   False       2     USA

#Store Merged Data in SQLite3

In [73]:
import sqlite3
conn = sqlite3.connect("spacex.db")

# Store DataFrame as table 'launches'
merge_df.to_sql("launches", conn, if_exists="replace", index=False)

print("Data successfully stored in SQLite database!")

q ="SELECT* FROM launches;"
result = pd.read_sql_query (q,conn)
result

Data successfully stored in SQLite database!

,name,date_utc,success,details,rocket,year,rocket_name,type,active,stages,country
0,FalconSat,2006-03-24 22:30:00+00:00,0.0,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,Falcon 1,rocket,0,2,China
1,DemoSat,2007-03-21 01:10:00+00:00,0.0,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,Falcon 1,rocket,0,2,Russia
2,Trailblazer,2008-08-03 03:34:00+00:00,0.0,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,Falcon 1,rocket,0,2,France
3,RatSat,2008-09-28 23:15:00+00:00,1.0,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,Falcon 1,rocket,0,2,Russia
4,RazakSat,2009-07-13 03:35:00+00:00,1.0,None,5e9d0d95eda69955f709d1eb,2009,Falcon 1,rocket,0,2,USA
...,...,...,...,...,...,...,...,...,...,...,...
200,Transporter-6,2022-12-01 00:00:00+00:00,NaN,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,1,2,France
201,TTL-1,2022-12-01 00:00:00+00:00,NaN,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,1,2,France
202,WorldView Legion 1 & 2,2022-12-01 00:00:00+00:00,NaN,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,1,2,Russia
203,Viasat-3 & Arcturus,2022-12-01 00:00:00+00:00,NaN,None,5e9d0d95eda69974db09d1ed,2022,Falcon Heavy,rocket,1,2,USA
204,O3b mPower 3.4,2022-12-01 00:00:00+00:00,NaN,None,5e9d0d95eda69973a809d1ec,2022,Falcon 9,rocket,1,2,France

##1.Launches by Country

In [64]:
q1 = "SELECT country, COUNT(*) AS total_launches FROM launches GROUP BY country\
 ORDER BY total_launches DESC;"
result = pd.read_sql_query (q1,conn)
result

  country  total_launches
0   China              45
1   India              43
2  France              41
3  Russia              40
4     USA              36

##2. Which year had the highest number of launches?

In [65]:
q2 = "SELECT year,COUNT(*) AS total_launches FROM launches GROUP BY year \
 ORDER BY total_launches DESC LIMIT 1;"
result = pd.read_sql_query (q2,conn)
result

   year  total_launches
0  2022              62

##3. Top 5 Missions by Launch Count

In [66]:
q3 = "SELECT name, COUNT(*) AS launch_count FROM launches GROUP BY name ORDER BY launch_count DESC LIMIT 5;"
result = pd.read_sql_query (q3,conn)
result

                        name  launch_count
0  ispace Mission 1 & Rashid             1
1                       ZUMA             1
2     WorldView Legion 1 & 2             1
3        Viasat-3 & Arcturus             1
4                    USSF-44             1